---

- name: Check for root directory/mount point
  stat:
    path: '{{ mount_point }}'
  register: mount


- name: Create root directory/mount point
  file:
    path: '{{ mount_point }}'
    owner: "{{ mount_owner }}"
    group: "{{ mount_group }}"
    mode: 0775
    state: directory

  when:
    - not unmount|default(false)
    - mount.stat.exists == false


- name: Prepare weblogic directories
  file:
    path: "{{ item }}"
    owner: "{{ wls_service_user.name }}"
    group: "{{ wls_service_user.group }}"
    mode: 0775
    state: directory
  with_items:
    - "{{ mount_point }}"
    - "{{ mount_point }}/app/oracle/middleware"
    - "{{ mount_point }}/app/oracle/config/domains"
    - "{{ mount_point }}/app/oracle/config/applications"
    - "{{ mount_point }}/software"
