---

- block:
    - name: Unpack patch set to build
      unarchive:
          src: "{{ mount_point }}/software/{{ patch_file.name }}.zip"
          dest: "{{ cache_path }}"
          remote_src: yes
      become: yes
      become_user: "{{ wls_service_user.name }}"
  when: patch_file.creates_file|default(false)

- block:
    - name: Unpack patch set to build
      unarchive:
          src: "{{ mount_point }}/software/{{ patch_file.name }}.zip"
          dest: "{{ cache_path }}"
          remote_src: yes
      become: yes
      become_user: "{{ wls_service_user.name }}"
  when: patch_file.creates_file|default(false)

- name: Install patch
  shell: "{{ patch_file.command }}"
  become: yes
  become_user: "{{  wls_service_user.name }}"
  register: patch
