---

- name: Load in our vars
  include_vars:
    file: main.yml
    name: weblogic_vars

- name: Create our users
  include: create-users.yml
  with_items: "{{ weblogic_vars.system_users }}"
  loop_control:
    loop_var: wls_service_user

- name: Create our mount point if it does not exist
  include: mount-point.yml
