---

- name: Load in our vars
  include_vars:
    file: main.yml
    name: weblogic_vars

- name: Create our users
  include: create-users.yml
  with_items: "{{ weblogic_vars.system_users }}"
  loop_control:
    loop_var: wls_service_user

- name: Create base directory structure
  include: create-directories.yml
  vars:
    - wls_service_user: "{{ weblogic_vars.system_users[0] }}"

- stat: "path={{ wls_home }}/server/bin/setWLSEnv.sh"
  register: wls_file

- block:
    - name: Get our WL artifacts from S3
      include: copy-artifacts.yml
      with_items: "{{ weblogic_artefacts }}"
      loop_control:
        loop_var: artefact
      vars:
        - wls_service_user: "{{ weblogic_vars.system_users[0] }}"
  when: wls_file.stat.exists == false
