---

- name: Check for mount
  stat:
    path: '{{ mount_point }}'
  register: mount


- name: Create mount point
  file:
    path: '{{ mount_point }}'
    owner: "{{ mount_owner }}"
    group: "{{ mount_group }}"
    mode: 0775
    state: directory

  when:
    - not unmount|default(false)
    - mount.stat.exists == false
