---

- name: Set patch facts
  set_fact:
    patch_number: "{{ patch_file.name.split('_')[0]|trim }}"
    cache_path: "{{ mw_home }}/utils/bsu/cache_dir"

- stat: "path={{ cache_path }}"
  register: cache_dir

- name: Create cache dir
  file:
    path: "{{ cache_path }}"
    owner: "{{ wls_service_user.name }}"
    group: "{{ wls_service_user.group }}"
    mode: 0775
    state: directory
  when:
    - cache_dir.stat.exists == false

- block:
    - name: Unpack patch set to build
      unarchive:
          src: "{{ mount_point }}/software/{{ patch_file.name }}.zip"
          dest: "{{ cache_path }}"
          remote_src: yes
      become: yes
      become_user: "{{ wls_service_user.name }}"
      creates: "{{ cache_path }}/{{ patch_file.creates }}"
  when: patch_file.creates|default(false)

- block:
    - name: Unpack patch set to build
      unarchive:
          src: "{{ mount_point }}/software/{{ patch_file.name }}.zip"
          dest: "{{ cache_path }}"
          remote_src: yes
      become: yes
      become_user: "{{ wls_service_user.name }}"
  when: patch_file.creates|default(false)

- name: Correct memory profile for bsu utility
  lineinfile:
    path: "{{ mw_home }}/utils/bsu/bsu.sh"
    regexp: '^MEM_ARGS='
    line: 'MEM_ARGS="-Xms2048m -Xmx2048m"'

- name: ensure permission on file are correct
  file:
    path: "{{ mw_home }}/utils/bsu/bsu.sh"
    mode: 0774

- name: Install patch
  shell: "{{ patch_file.command }}"
  become: yes
  become_user: "{{  wls_service_user.name }}"
  register: patch