---

- name: Create service startup template for admin server
  become: yes
  become_user: "root"
  template:
    src: 'weblogic.service.j2'
    dest: '/etc/systemd/system/weblogic.service'
    mode: '0644'
    owner: "root"
    group: "root"

- name: Reload the (new) service which will also start it
  become: yes
  become_user: "root"
  systemd:
    name: weblogic.service
    state: reloaded
    enabled: yes
    daemon_reload: yes
